name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: npx percy snapshot ./pages.yml
        working-directory: ./
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
