name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test
        run: npm run test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
